### ISSUE TITLE
Cards are never Shuffled

### ISSUE THREAD

**Issue by vivek1996** [elharony/Udacity-Study-Jam-FEND-P3-Memory-Game#1]
The cards need to  be shuffled at every restart of the game but your code does not shuffle the cards and has the same order of cards at every refresh

**Comment by elharony** [comment]
Hi @vivek1996 

Well, if you read the `README` file you will notice that under `Does it cover everything?` headline, I wrote the following:
`
`shuffle` the cards. It is self-assigned; All you need to do is to use the provided shuffle function, then loop through the icons after being shuffled!
`

Thanks for pointing this out! 👍
